extends: default

rules:
  document-start: disable
  line-length: disable
  comments:
    min-spaces-from-content: 1
  truthy:
    check-keys: false
ignore:
  - .travis.yml
  - crypto/secp256k1/libsecp256k1/.travis.yml
