name: golangci-lint

on:
  push:
    branches: [main, "release/**"]
  pull_request:
    branches: [main, "release/**"]
  workflow_dispatch:

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          only-new-issues: true
          # The goheader linter is enabled so that it runs only on modified or new files
          # (see only-new-issues: true). Note it is disabled in .golangci.yml because
          # golangci-lint is not aware of new/modified files compared to the last git commit,
          # and we want to avoid reporting invalid goheader errors when running the linter locally.
          args: --enable goheader
